apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: emptydir
      mountPath: /mount1
  - name: nginx
    image: nginx
    volumeMounts:
    - name: emptydir
      mountPath: /mount2
  volumes:
  - name : emptydir
    emptyDir: {}
