apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: rs1-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.0
