apiVersion: v1
kind: Pod
metadata:
  name: lr-pod
  namespace: lr-ns
spec:
  containers:
  - name: container
    image: ubuntu
    resources:
      requests:
        memory: 0.1Gi
      limits:
        memory: 0.5Gi
